Add support for service principal authentication
webdevops/azure-devops-exporter pull request #77
Opened 2024-02-25 15:59 UTC by moredatapls

Fixes #71

2024-03-04 14:33 UTC, nevembalint approved these changes

2024-03-05 09:28 UTC, balcsida commented
Sorry to ping you directly, @mblaschke, but if you have the chance, could you please check this matter out?

2024-03-05 09:49 UTC, balcsida commented on .vscode/launch.json
Hey @moredatapls ,

I've been reviewing the changes in this pull request and I noticed that IDE-specific files like .vscode/launch.json have been included. Typically, these files are personal to each developer's environment and might not be necessary or beneficial for the project as a whole. It's often a good practice to exclude them from the project repository to keep the codebase clean and ensure that each contributor's setup remains flexible.

Could you please kindly remove this file from this pull request?

Kind regards,
@balcsida

2024-03-05 09:50 UTC, balcsida requested changes

2024-03-05 09:50 UTC, balcsida commented on .vscode/launch.json
Hey @moredatapls ,

I've been reviewing the changes in this pull request and I noticed that IDE-specific files like .vscode/launch.json have been included. Typically, these files are personal to each developer's environment and might not be necessary or beneficial for the project as a whole. It's often a good practice to exclude them from the project repository to keep the codebase clean and ensure that each contributor's setup remains flexible.

Could you please kindly remove this file from this pull request?

Kind regards,
@balcsida

2024-03-31 09:41 UTC, merged